- hosts: all
  gather_facts: False
   
  tasks:
  - name: install python 2
    become: yes
    raw: apt -y update && apt install -y python-minimal

- hosts: wordpress

  roles:
    - server
    - php
    - mysql
    - wordpress