---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  become: yes

- name: Extract WordPress
  unarchive:
    src=/tmp/wordpress.tar.gz dest=/var/www/
    copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file 1
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: 'database_name_here'
    replace: '{{wp_mysql_db}}'
  become: yes
- name: Update WordPress config file 2
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: 'username_here'
    replace: '{{wp_mysql_user}}'
    backup: no
  become: yes
- name: Update WordPress config file 3
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: 'password_here'
    replace: '{{wp_mysql_password}}'
    backup: no
  become: yes